version: "3.3"

services:
  mssql-db:
    image: mcr.microsoft.com/mssql/server
    restart: always
    ports:
      - 5000:1433
    environment: 
      ACCEPT_EULA: Y
      SA_PASSWORD: "HelloW0rld"
  
  application:
    image: mrbacky/workouter
    environment: 
      ASPNETCORE_ENVIRONMENT: Development
    depends_on: 
      - mssql-db
    ports: 
      - 5001:80