version: "3.3"

services:
  mssql-db-5:
    build: ./db/docker
    restart: always
    ports:
      - 50000:1433
    environment: 
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "HelloW0rld"
      MSSQL_DB: Workouter
    
  application:
    image: mrbacky/workouter
    environment: 
      ASPNETCORE_ENVIRONMENT: Development
    depends_on: 
      - mssql-db-5
    ports: 
      - 50001:80

  flyway:
    image: flyway/flyway
    command: migrate
    volumes:
      - ./db:/flyway/sql
      - ./db:/flyway/conf
    depends_on:
      - mssql-db-5


