version: "3.3"

services:
  mssql-db-5:
    image: mcr.microsoft.com/mssql/server
    restart: always
    ports:
      - 50000:1433
    environment: 
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "HelloW0rld"
  
  application:
    image: mrbacky/workouter
    environment: 
      ASPNETCORE_ENVIRONMENT: Development
    depends_on: 
      - mssql-db-5
    ports: 
      - 50001:80