version: "3.3"

services:
  mssql-db-5:
    image: mcr.microsoft.com/mssql/server
    restart: always
    volumes: 
      - ./db/data:/var/opt/mssql
    environment: 
      MYSQL_ROOT_PASSWORD: group5Passw0rd
      MYSQL_DATABASE: ContactBook5
    ports:
      - 5100:1433
   